# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Australia', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='matt', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(default='matt', max_length=100),
            preserve_default=False,
        ),
    ]
