# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='_profile_connections_+', to='api.Profile'),
        ),
    ]
