# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160926_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdescription',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
            preserve_default=False,
        ),
    ]
