# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_employmentdescription_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdescription',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='educationdescription',
            name='extra_activities',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='educationdescription',
            name='field_of_study',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
