# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161009_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdescription',
            name='date_started',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationdescription',
            name='date_attained',
            field=models.DateField(blank=True, null=True),
        ),
    ]
