# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_employmentdescription_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentdescription',
            name='employer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentdescription',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
