# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
