# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_feedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='profile',
        ),
        migrations.AddField(
            model_name='feedpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
