# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20161022_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
